#!/usr/bin/env node
/**
 * scrape.js
 * ===========================================================================
 * Scrapes the OFFICIAL Hamburg Ballett calendar and writes every upcoming
 * performance to database/events/hamburg.json.
 *
 * Source of truth (official site):
 *   https://www.hamburgballett.de/de/kalender/ballett
 *   (this URL is served by hamburgballett.die-hamburgische-staatsoper.de,
 *    the CMS that powers hamburgballett.de — it is the same official site,
 *    just multi-domain hosted by Die Hamburgische Staatsoper)
 *
 * Why Playwright instead of Cheerio?
 *   The calendar renders its month-by-month event list using client-side
 *   JavaScript (month tabs, "load more" style navigation). A plain HTTP GET
 *   + Cheerio parse would only see a partial/empty shell in the worst case,
 *   so we drive a real headless browser, wait for the calendar to render,
 *   and page through the following months by clicking the "next month"
 *   control until no more events are found.
 *
 * Resilience strategy (IMPORTANT — read before "fixing" selectors):
 *   The site's CSS class names are auto-generated by its CMS/build tooling
 *   and can change at any time without notice. Instead of depending on
 *   specific class names, this scraper:
 *     1. Finds candidate event containers by looking for the SMALLEST
 *        element that contains exactly ONE date/time text pattern
 *        (e.g. "Sa 5.9.26 16:30"). This is robust to class renames because
 *        it relies on the human-readable text pattern, not markup.
 *     2. Extracts venue/category/title by walking the plain text lines of
 *        that container in order, relative to the date/time line — again
 *        text-position based, not class based.
 *     3. Extracts the ticket URL and performance detail URL by looking for
 *        links whose VISIBLE TEXT is "Tickets"/"Anmeldung" (ticket link) or
 *        "Details" (performance detail link), rather than by CSS selector.
 *   If the site is redesigned enough that this text-based approach breaks,
 *   the script fails loudly (throws / exits non-zero) rather than silently
 *   writing an empty or garbled file, so a scheduled run's failure is
 *   obvious in GitHub Actions logs.
 * ===========================================================================
 */

const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

// Official Hamburg Ballett calendar, filtered to the "Ballett" category only
// (the site also has combined Oper/Konzert calendars we don't want).
const CALENDAR_URL = 'https://www.hamburgballett.de/de/kalender/ballett';

// Safety cap on how many "next month" clicks we perform, so a bug in the
// pagination-detection logic can never turn into an infinite loop.
const MAX_MONTH_PAGES = 30;

// Where the final JSON database lives.
const OUTPUT_PATH = path.join(__dirname, '..', 'database', 'events', 'hamburg.json');

// German weekday abbreviations used by the site, e.g. "Sa 5.9.26 16:30".
const WEEKDAYS = 'Mo|Di|Mi|Do|Fr|Sa|So';

// Matches things like "Sa 5.9.26 16:30" or "So 27.12.26 14:00".
// Captures: day, month, 2-or-4-digit year, hour, minute.
const DATE_TIME_RE = new RegExp(
  `(?:${WEEKDAYS})\\s+(\\d{1,2})\\.(\\d{1,2})\\.(\\d{2,4})\\s+(\\d{2}):(\\d{2})`
);

// Category labels the site uses for this calendar (kept in case the ballet
// calendar ever mixes in other categories, e.g. during shared festivals).
const CATEGORY_LABELS = ['Ballett', 'Oper', 'Konzert'];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Turn a title into a URL/ID-safe slug. */
function slugify(str) {
  return str
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '') // strip accents (é -> e, etc.)
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/** Normalize a 2- or 4-digit year to a 4-digit year. */
function normalizeYear(y) {
  if (y.length === 4) return y;
  const n = parseInt(y, 10);
  return String(2000 + n);
}

/** Zero-pad a number to 2 digits. */
function pad2(n) {
  return String(n).padStart(2, '0');
}

// ---------------------------------------------------------------------------
// Core extraction, run INSIDE the browser page (page.evaluate) so we can walk
// the live DOM directly. Everything here is plain, dependency-free JS because
// it executes in the browser context, not in Node.
// ---------------------------------------------------------------------------

function extractEventsFromPage(dateTimeReSource, categoryLabels) {
  const dateTimeRe = new RegExp(dateTimeReSource);
  const globalDateTimeRe = new RegExp(dateTimeReSource, 'g');

  const results = [];

  // Candidate containers: every <li> on the page. We filter down to the
  // ones that represent exactly one event (see module doc comment above).
  const allLis = Array.from(document.querySelectorAll('li'));

  for (const li of allLis) {
    const text = (li.innerText || '').trim();
    if (!text) continue;

    const matches = text.match(globalDateTimeRe);
    if (!matches || matches.length !== 1) continue; // 0 = no date, >1 = wrapper with several events

    // Must also contain at least one link to a performance/detail page,
    // otherwise it's probably just incidental matching text.
    const links = Array.from(li.querySelectorAll('a[href]'));
    const programLinks = links.filter((a) => /\/programm\//.test(a.getAttribute('href') || ''));
    if (programLinks.length === 0) continue;

    // Split into non-empty trimmed lines, in DOM order, to locate fields
    // positionally relative to the date/time line.
    const lines = text
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean);

    const dateLineIdx = lines.findIndex((l) => dateTimeRe.test(l));
    if (dateLineIdx === -1) continue;

    // Venue is the line immediately following the date/time line.
    const venue = lines[dateLineIdx + 1] || null;

    // Category ("Ballett"/"Oper"/"Konzert") is the next line, after the
    // venue, that exactly matches one of the known category labels. There
    // may be a festival name line in between (e.g. "52. Hamburger
    // Ballett-Tage"), which we simply skip over.
    let categoryLineIdx = -1;
    let category = null;
    for (let i = dateLineIdx + 2; i < Math.min(lines.length, dateLineIdx + 6); i++) {
      if (categoryLabels.includes(lines[i])) {
        categoryLineIdx = i;
        category = lines[i];
        break;
      }
    }

    // Title is the line right after the category line. If we couldn't find
    // a category line (unexpected layout), fall back to the first program
    // link's own text, which is usually the title.
    let title = categoryLineIdx !== -1 ? lines[categoryLineIdx + 1] : null;
    if (!title) {
      const firstNonDetailLink = programLinks.find(
        (a) => a.innerText.trim() && a.innerText.trim() !== 'Details'
      );
      title = firstNonDetailLink ? firstNonDetailLink.innerText.trim() : null;
    }
    if (!title) continue; // can't build a usable record without a title

    // Some entries (CLICK-in / Patenklassen formats) show a generic link
    // label like "Patenklassen Ballett" with the actual production name as
    // a short line right after it (e.g. "A Cinderella Story"). If the line
    // after our detected "title" line is short and is NOT a ticket/details
    // label and NOT the start of a longer description, fold it in for
    // clarity. This is a best-effort heuristic, not required for basic
    // correctness.
    const nextLine = categoryLineIdx !== -1 ? lines[categoryLineIdx + 2] : null;
    const NON_SUBTITLE_MARKERS = /^(Tickets|Anmeldung|Details|Für|Ab |ab )/;
    if (
      nextLine &&
      nextLine.length > 0 &&
      nextLine.length <= 60 &&
      !NON_SUBTITLE_MARKERS.test(nextLine) &&
      !dateTimeRe.test(nextLine)
    ) {
      // Heuristic: only fold in when the "title" line itself looks like a
      // generic program-format name rather than a specific work title.
      const GENERIC_TITLES = ['Patenklassen Ballett', 'BallettInsider:innen', 'Sneak Klub', 'Werkstatt der Kreativität XVII'];
      if (GENERIC_TITLES.some((g) => title.startsWith(g))) {
        title = `${title} – ${nextLine}`;
      }
    }

    // Ticket link: an <a> whose visible text is "Tickets" or "Anmeldung".
    // If its href is just "#" (placeholder meaning "not yet on sale" or
    // "sold out"), we record null instead of a dead link.
    const ticketLink = links.find((a) => /^(Tickets|Anmeldung)$/i.test(a.innerText.trim()));
    let ticketUrl = null;
    if (ticketLink) {
      const href = ticketLink.getAttribute('href') || '';
      if (href && href !== '#') {
        ticketUrl = new URL(href, window.location.href).toString();
      }
    }

    // Performance detail URL: prefer the link explicitly labeled "Details",
    // otherwise fall back to the first /programm/ link (usually the title
    // link itself).
    const detailsLink = links.find((a) => a.innerText.trim() === 'Details');
    const urlSourceLink = detailsLink || programLinks[0];
    const url = urlSourceLink
      ? new URL(urlSourceLink.getAttribute('href'), window.location.href).toString()
      : null;
    if (!url) continue;

    const m = matches[0].match(dateTimeRe);
    const [, day, month, year, hour, minute] = m;

    results.push({
      title,
      venue,
      day,
      month,
      year,
      hour,
      minute,
      ticketUrl,
      url,
    });
  }

  return results;
}

// ---------------------------------------------------------------------------
// Month pagination: repeatedly click the "next month" (→) control and
// re-extract, until either no new events appear or we hit MAX_MONTH_PAGES.
// The control is identified by its visible arrow text/aria-label rather than
// a CSS class, again for resilience.
// ---------------------------------------------------------------------------

async function clickNextMonth(page) {
  // Try a handful of resilient ways to find the "next month" control.
  const candidates = [
    page.getByRole('link', { name: '→' }),
    page.getByRole('button', { name: '→' }),
    page.locator('a:has-text("→")'),
    page.locator('button:has-text("→")'),
    page.locator('[aria-label*="next" i]'),
    page.locator('[aria-label*="nächst" i]'),
  ];

  for (const locator of candidates) {
    try {
      const count = await locator.count();
      if (count > 0) {
        const el = locator.last(); // the visible "advance" arrow tends to be the last match
        if (await el.isVisible().catch(() => false)) {
          await el.click({ timeout: 3000 }).catch(() => {});
          return true;
        }
      }
    } catch (_) {
      // try next candidate strategy
    }
  }
  return false;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function scrape() {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    userAgent:
      'Mozilla/5.0 (compatible; HamburgBalletDatabaseBot/1.0; +https://github.com/)',
    locale: 'de-DE',
  });
  const page = await context.newPage();

  console.log(`Navigating to ${CALENDAR_URL} ...`);
  await page.goto(CALENDAR_URL, { waitUntil: 'networkidle', timeout: 60000 });

  // Give any lazy client-side rendering a moment to settle.
  await page.waitForTimeout(1500);

  const collected = new Map(); // dedupe key -> raw event

  let stableRounds = 0;
  for (let pageIndex = 0; pageIndex < MAX_MONTH_PAGES; pageIndex++) {
    const before = collected.size;

    const raw = await page.evaluate(extractEventsFromPage, DATE_TIME_RE.source, CATEGORY_LABELS);
    for (const ev of raw) {
      const year = normalizeYear(ev.year);
      const date = `${year}-${pad2(ev.month)}-${pad2(ev.day)}`;
      const time = `${pad2(ev.hour)}:${pad2(ev.minute)}`;
      // Dedup key: title + date + time is unique enough for this calendar.
      const key = `${ev.title}__${date}__${time}`;
      if (!collected.has(key)) {
        collected.set(key, { ...ev, date, time });
      }
    }

    const after = collected.size;
    if (after === before) {
      stableRounds++;
    } else {
      stableRounds = 0;
    }

    // Stop once a couple of consecutive "next month" clicks stop yielding
    // new events (either we've run out of published months, or pagination
    // isn't wired the way we expect and we should bail out gracefully).
    if (stableRounds >= 2) break;

    const advanced = await clickNextMonth(page);
    if (!advanced) break;
    await page.waitForTimeout(1200); // allow the new month's events to render
  }

  await browser.close();

  if (collected.size === 0) {
    throw new Error(
      'No events were extracted. The official site may have changed its markup ' +
        'beyond what this scraper\'s text-based heuristics can handle — check ' +
        'CALENDAR_URL manually before assuming the ballet has no upcoming shows.'
    );
  }

  // -------------------------------------------------------------------------
  // Build final records in the required shape, filter to upcoming only, and
  // sort chronologically.
  // -------------------------------------------------------------------------
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${pad2(now.getMonth() + 1)}-${pad2(now.getDate())}`;

  const events = Array.from(collected.values())
    .filter((ev) => ev.date >= todayStr) // "upcoming" only
    .map((ev) => ({
      id: `${slugify(ev.title)}-${ev.date}-${ev.time.replace(':', '')}`,
      company: 'Hamburg Ballett',
      city: 'Hamburg',
      title: ev.title,
      date: ev.date,
      time: ev.time,
      venue: ev.venue,
      ticketUrl: ev.ticketUrl,
      url: ev.url,
    }));

  events.sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time));

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(events, null, 2) + '\n', 'utf-8');

  console.log(`Wrote ${events.length} upcoming events to ${OUTPUT_PATH}`);
}

scrape().catch((err) => {
  console.error('Scrape failed:', err);
  process.exit(1);
});
